### ISSUE TITLE
there are errors in this project 

### ISSUE THREAD

**Issue by Eng-Mushtaq** [madeeldev/flutter-doctor-consultation-app#1]
The method 'AuthService' isn't defined for the type '_ForgotPasswordPageState'.
Try correcting the name to the name of an existing method, or defining a method named 'AuthService'.

Undefined name 'Config'.
Try correcting the name to one that is defined, or defining the name.

Target of URI doesn't exist: '../../services/auth_service.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

**Comment by madeeldev** [comment]
For security reasons, the AuthService and Config files are excluded from this repository due to sensitive credentials.

If access to these files is required, please contact us via email. We can provide sanitized versions removing credentials, along with JSON samples of the data returned by those services.

This ensures project functionality without compromising security.
